services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auctions
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123456
    ports:
      - "27017:27017"
    volumes:
      - /data/db




#--------------------------------------------------------------
# first step in docker compose for creating database (postgres)
# the run update command -> $ dotnet ef database update
#--------------------------------------------------------------

#services:
#  postgres:
#    image: postgres
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=auctions
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:





#--------------------------------------------------------------
# specified volume data
#--------------------------------------------------------------

#services:
#  postgres:
#    image: postgres
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=auctions
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  mongodb:
#    image: mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=mongo123456
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodata:/data/db
#
#volumes:
#  pgdata:
#  mongodata:

